server:
  port: 3099
  servlet:
    context-path: /exphub
  forward-headers-strategy: native

spring:
  application:
    name: ExpHub

  datasource:
    url: jdbc:mysql://cloudim.club:3306/exphub?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: ***CHANGED***
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5


    host: cloudim.club
    port: 6379
    database: 0
    timeout: 5000ms


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  ai:
    mcp:
      server:
        name: exphub
        version: 1.0.0
        type: sync
        stdio: false
        sse:
          message-endpoint: /mcp/message
          endpoint: /mcp/sse

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.security: DEBUG
    com.exphub: DEBUG
